### ISSUE TITLE
loop of first 20 search outputs

### ISSUE THREAD

**Issue by zenny** [trizen/straw-viewer#1]
@trizen Great work!

I liked the new output interface in cli mode except it would be nice if the search outputs displays the date of video posted (than duration passed in d/m/y) and the number of comments (a feature request).

Unlike youtube-viewer, straw-viewer only shows first 20 outputs and keeps on looping the same first results when pressed <enter> for the next 20. Or did I miss anything?

Cheers,
/z

**Comment by trizen** [comment]
Thanks, @zenny!

This project is currently very experimental and some features are not implemented yet. This includes the support for the next pages of results.

I will try to sort this issue out in the near future.

**Comment by trizen** [comment]
Fixed in https://github.com/trizen/straw-viewer/commit/3bb78645fd553b3d58b222931c4828e373cc49c3. Thanks for reporting.

The layout of results can be changed in the configuration file (`~/.config/straw-viewer/straw-viewer.conf`), by modifying the `custom_layout_format` entry.

The supported tokens are documented in `straw-viewer -T`.

**Comment by zenny** [comment]
> Fixed in [3bb7864](https://github.com/trizen/straw-viewer/commit/3bb78645fd553b3d58b222931c4828e373cc49c3). Thanks for reporting.
> 
> The layout of results can be changed in the configuration file (`~/.config/straw-viewer/straw-viewer.conf`), by modifying the `custom_layout_format` entry.
> 
> The supported tokens are documented in `straw-viewer -T`.

@trizen Thanks, but my `~/.config/straw-viewer/straw-viewer.conf` is empty file, to my surprise!

**Comment by zenny** [comment]
> Fixed in [3bb7864](https://github.com/trizen/straw-viewer/commit/3bb78645fd553b3d58b222931c4828e373cc49c3). Thanks for reporting.
> 
> The layout of results can be changed in the configuration file (`~/.config/straw-viewer/straw-viewer.conf`), by modifying the `custom_layout_format` entry.
> 
> The supported tokens are documented in `straw-viewer -T`.

@trizen Thanks for the inputs. Highly appreciated.
