### ISSUE TITLE
Permission denied at /usr/share/perl5/site_perl/WWW/StrawViewer.pm line 381.

### ISSUE THREAD

**Issue by zenny** [trizen/straw-viewer#11]
Hi @trizen 

I am at:

```
$ straw-viewer --version
CLI Straw Viewer 0.0.3
```

But straw-viewer started spilling out the following error from this morning (was working alright till yesterday, fyi):

```
$ straw-viewer --debug coronavirus
** GET https://invidio.us/api/v1/search?maxResults=20&part=snippet&q=coronavirus&type=video ==> 200 OK (1s)
open('/tmp/straw-viewer/327c69828d3a7e7ae9ab52c2d15b9b47', 'w'): Permission denied at /usr/share/perl5/site_perl/WWW/StrawViewer.pm line 381.

[!] No video results!

=>> Select one or more videos to play (:h for help)
> ^C
```
Line 381 in /usr/share/perl5/site_perl/WWW/StrawViewer.pm reads like:

```
    my $response   = $self->{lwp}->get($url, %lwp_header);
```

Any clue?

Cheers and stay safe,
/z

**Comment by zenny** [comment]
@trizen This issued popped up once again from this afternoon:

```
$ straw-viewer --debug coronavirus
** GET https://invidio.us/api/v1/search?maxResults=20&part=snippet&q=coronavirus&type=video ==> 200 OK (1s)
open('/tmp/straw-viewer/a966bb046d7eef5687653eeb3f471fbe', 'w'): Permission denied at /usr/share/perl5/site_perl/WWW/StrawViewer.pm line 381.

[!] No video results!

=>> Select one or more videos to play (:h for help)
> 
```

Cheers and stay safe,
/z

**Comment by trizen** [comment]
Try removing the config file of straw-viewer. Or simply change the cache directory to some other directory where you have read and write permissions.

**Comment by zenny** [comment]
> Try removing the config file of straw-viewer. Or simply change the cache directory to some other directory where you have read and write permissions.

@trizen Thanks for the prompt answer.

/tmp has r+w permissions and not an issue:

```
$ touch /tmp/straw-viewer/newfile
$ ls -la /tmp/straw-viewer
total 4.0K
drwxr-xr-x 2 zenny-nowm zenny-nowm   80 May 27 13:30 .
drwxrwxrwt 8 root       root        220 May 27 13:30 ..
-rw-r--r-- 1 zenny-nowm zenny-nowm 1.1K May 27 13:26 b9d2edc9e6c3cd6383a6d5597166e958
-rw-r--r-- 1 zenny-nowm zenny-nowm    0 May 27 13:30 newfile
```

removing `straw-viewer.conf` gave and output:

```
]$ straw-viewer --debug coronavirus
** GET https://invidio.us/api/v1/search?maxResults=20&part=snippet&q=coronavirus&type=video ==> 200 OK (1s)

[!] No video results!

=>> Select one or more videos to play (:h for help)
> 
```
Both ways it didn't work, fyi!

**Comment by trizen** [comment]
I cannot reproduce the "permission denied" issue, but I can reproduce the "no video results" issue.

Sometimes, `invidio.us` gets too crowded and fails to work. When this happens, we can change the API host to some other instance of invidious, such us https://invidious.snopyta.org/

The available instances are listed at: https://instances.invidio.us/

```console
straw-viewer --api-host=invidious.snopyta.org --debug coronavirus
```

This can be changed permanently, by setting in the config-file:

```perl
  api_host => "https://invidious.snopyta.org",
```

**Comment by zenny** [comment]
> ```
> straw-viewer --api-host=invidious.snopyta.org --debug coronavirus
> ```

Yep, the latter with `--api-host` flag works as desired. Thanks for the pointer to list of api-hosts. Fantastic work, @trizen !
