### ISSUE TITLE
Cannot get autoplay feature to work

### ISSUE THREAD

**Issue by aearil** [trizen/straw-viewer#15]
Hello ! First of all, thank you for this really nice piece of software ! :)

That said I'm having trouble figuring out how to use the autoplay feature. I've tried the following methods:
* with the following, at the end of the first video, no other video starts playing:
```
$ straw-viewer -n --autoplay <search terms>
> 1
```

* Here all the search results are played in order (which I guess is fair):
```
$ straw-viewer -n --autoplay -A <search terms>
```

* Same as the first one: video ends then nothing happens:
```
$ straw-viewer -n --autoplay "https://www.youtube.com/watch?v=65As1V0vQDM"
```

* No luck either via the CLI:
```
$ straw-viewer -n
> <search terms>
> :autoplay=1
```

Am I doing this wrong or is the feature broken/not fully implemented ?

**Comment by trizen** [comment]
Hi. I'm glad you find straw-viewer useful. :)

I just added basic support for related videos, which also implements `--autoplay`, which was previously not implemented.

Thanks for reporting the issue!

**Comment by aearil** [comment]
Thank you very much for the swift answer and implementation !

Just tried it, it works perfectly :)
