### ISSUE TITLE
Config file colors setting has no affect.

### ISSUE THREAD

**Issue by akiva** [trizen/straw-viewer#16]
The default config file does not affect output yet the `-C` argument does.

In `~/.config/straw-viewer/straw-viewer.conf`:

```
...
colors                => 1,
...
```

**Comment by trizen** [comment]
When set to zero, colors will be disabled. The behavior of `-C` can be activated with:

```perl
results_with_colors => 1,
```

but make sure that:

```perl
  results_fixed_width   => 0,
  results_with_details  => 0,
```

**Comment by akiva** [comment]
Interesting, what does `colors => 1` do then? I had somehow missed the specific `results_with_colors`. Thanks!

**Comment by trizen** [comment]
Setting `colors => 0` disables support for colors entirely. Useful for terminals that do not support ANSI colors, or for people that do not like colors.

Relevant portion of code: https://github.com/trizen/straw-viewer/blob/master/bin/straw-viewer#L1187..L1200

**Comment by akiva** [comment]
@trizen Thanks for the clarification and all your work on the project. I'm thoroughly enjoying it as an alternative to `youtube-viewer`. Cheers.
