### ISSUE TITLE
Undefined subroutine

### ISSUE THREAD

**Issue by arankaren** [trizen/straw-viewer#2]
Hello dear friend, I am testing this application. But I get this message

```
$ gtk-straw-viewer
[Mon Mar  2 09:55:27 2020]:
Undefined subroutine &List::Util::uniq called at /usr/bin/vendor_perl/gtk-straw-viewer line 651.
```
the cli application works fine, the issue occurs with gtk-straw-viewer

**Comment by trizen** [comment]
Looks like you have a pretty old version of Perl / [List::Util](https://metacpan.org/pod/List::Util).
