### ISSUE TITLE
the -sc (channel search) flag produces a bunch of errors

### ISSUE THREAD

**Issue by JustAnotherStrange** [trizen/straw-viewer#20]
When I try to search for channels, I get a bunch of errors. If I select one of them, it still works, but in the menu I cannot see what any of the channels are/
![Example search](https://user-images.githubusercontent.com/64844168/87733668-729eee80-c79e-11ea-8a77-df6b68834498.png)
![After selecting channel 1](https://user-images.githubusercontent.com/64844168/87733716-8cd8cc80-c79e-11ea-8f61-3b1623d83ad7.png)
So the feature works, it just doesn't display the channels in the search.

**Comment by trizen** [comment]
Thanks for reporting the issue.
