### ISSUE TITLE
Weird message that appears once every few searches

### ISSUE THREAD

**Issue by pitsi** [trizen/straw-viewer#21]
After the upgrade to 0.0.6, straw viewer pops up this message once every few searches
`[JSON]: , or } expected while parsing object/hash, at character offset 144465 (before "endscreenClick":+["h...") at /home/user/lib/WWW/StrawViewer/ParseJSON.pm line 34.`
It does not seem to affect anything, since playback and search both work fine, but I thought I should mention it.

Straw viewer 0.0.6, youtube-dl 2020.06.16.1, perl 5.30.3, mpv 0.32 as the player and all that on a machine running debian testing x64.
Since my distro does not package it, I have put the binary inside ~/bin and its libraries in ~/lib and I have this bit in my .bashrc to make it work
```
PATH=$PATH:$HOME/bin/
PERL5LIB=$HOME/lib;export PERL5LIB
```
It has been like that since I started using youtube viewer on my machine, 5+ years ago, and it works flawlessly.

**Comment by trizen** [comment]
I'm not quite sure why this happens. Most likely it's an YouTube issue. I will have to investigate this more deeply to see if this can be fixed in straw-viewer or the warning should just be hidden.

Same as: https://github.com/trizen/straw-viewer/issues/3
