### ISSUE TITLE
Invidio.us shuts down on October 1st

### ISSUE THREAD

**Issue by pitsi** [trizen/straw-viewer#23]
I was reading reddit earlier and I came accross this, so I thought I should mention it here since straw-viewer will probably stop working after that date

https://omar.yt/posts/stepping-away-from-open-source

---edit
It seems that the site will be shut down on September 1st. The api will be shut down on October 1st, so I changed the title.

**Comment by OrionRandD** [comment]
From my experience here, I have found that 
https://instances.invidio.us/ -> yewtu.be
Is much more responsive than invidious.snopyta.org

Using invidious.snopyta.org has given me lots of 
"! no stream URL has been found error..."
How do I set yewtu.be to be the default here?
Thx a lot

**Comment by trizen** [comment]
See: https://github.com/trizen/straw-viewer#invidious-instances

For me, `invidious.fdn.fr` and `invidious.13ad.de` seem to work the best.

I'm considering adding support for `--instance=auto`, which would automatically pick an instance from the top ones.

**Comment by OrionRandD** [comment]
Do that, please :)
This appl is really wonderful.
How should I update it when you add the auto instance?
Should I "git pull"?
Where exactlly?
:)

**Comment by trizen** [comment]
For using the development version, see: https://github.com/trizen/straw-viewer#try

If you're using Arch Linux, then you can simply reinstall "straw-viewer-git" from the AUR.

**Comment by OrionRandD** [comment]
Nope. Debian here....

**Comment by pitsi** [comment]
> See: https://github.com/trizen/straw-viewer#invidious-instances
> 
> For me, `invidious.fdn.fr` and `invidious.13ad.de` seem to work the best.
> 
> I'm considering adding support for `--instance=auto`, which would automatically pick an instance from the top ones.

Is this the same as the `--api-host` parameter in ~/.config/straw-viewer/straw-viewer.conf? 

Mine seems to mention `invidio.us` in there, but straw-viewer has been really slow in getting results and starting playback. Launching it with the --debug option says that it is using `invidious.snopyta.org`.

**Comment by trizen** [comment]
Yes, `--api`, `--api-host` and `--instance` are all the same.

Since `invidio.us` is getting shut down, straw-viewer is now replacing `invidio.us` with `invidious.snopyta.org`. (https://github.com/trizen/straw-viewer/commit/4807a31de7eeb897002aa16436b970b3f131bb8a)

Maybe picking a random instance would be a clever thing to do?

**Comment by pitsi** [comment]
Does anyone else get this or is it just me? 
429 error on yewtu.be
```
$ straw-viewer 

=>> Search for YouTube videos (:h for help)
> idies proseuxes
[429 Too Many Requests] Error occurred on URL: https://yewtu.be/api/v1/search?maxResults=20&part=snippet&q=idies%20proseuxes&type=video

[!] No video results!

:: Probably yewtu.be is down. Try:

	/home/user/bin/straw-viewer --api=invidious.13ad.de

See also: https://github.com/trizen/straw-viewer#invidious-instances
```
and a 500 error on invidious.13ad.de, which looks similar to the above.
```
$ straw-viewer --api=invidious.13ad.de

=>> Search for YouTube videos (:h for help)
> idies proseuxes
[500 Server closed connection without sending any data back] Error occurred on URL: https://invidious.13ad.de/api/v1/search?maxResults=20&part=snippet&q=idies%20proseuxes&type=video

[!] No video results!

:: Probably invidious.13ad.de is down. Try:

	/home/user/bin/straw-viewer --api=invidious.13ad.de

See also: https://github.com/trizen/straw-viewer#invidious-instances
```
Last time I posted here 6 days ago, I changed the api line inside strawviewer.conf to `invidious.13ad.de`, but once I got the second error last night I changed it to `yewtu.be`, but no luck with both. In fact, `invidious.13ad.de` is not even listed in the instances page now!
The 'invidious.snopyta.org', 'invidious.tube' and 'invidious.xyz' instances seem to work for now. I did not test the rest.

**Comment by trizen** [comment]
Same errors here.

It looks like yewtu.be disabled the access to the API on purpose, while `invidious.13ad.de` moved to another server (see: https://magnum.hallertau.social/channel/badde/)

`invidious.13ad.de` got unlisted 11 days ago at the request of the maintainer, because of a "significant rise on bandwidth" (see: https://github.com/iv-org/invidious/wiki/Invidious-Instances/_history).

**Comment by OrionRandD** [comment]
I've noticed that it will be difficult to use this straw-viewer
from now on after the omaroh dev dropped invidious...
Such a wonderful app, this one...
It is really annoying to keep guessing and trying new instances,
Then instances move away, do not work, disappear, etc...
:(

**Comment by OrionRandD** [comment]
Hi, 
Is there a way of add a code in straw-viewer to choose an option out of
a list when a instance fail? Like so:

$ straw-viewer
$ Which instance would you like to use?
a) yewtu.be
b) invidious.snopyta.de
c) invidious.13ad.de
e) etc...

It would make more sense than to suggest only another instance...

Thanks anyway...

-----------

**Comment by trizen** [comment]
There is `--api=auto` in version `0.0.9` (soon to be released), which automatically picks a random working instance.

See: https://github.com/trizen/straw-viewer#invidious-instances

**Comment by OrionRandD** [comment]
@trizen great! Thx

**Comment by OrionRandD** [comment]
What do you guys think of this instance?
It asks for bitcoins.
Do you know if it has cryptomining acting behind it to mine computers where
it is being used?

https://invidious.tube

Thx

**Comment by OrionRandD** [comment]
The reason I asked is because when I use this instance,

invidious.tube

My CPU spins crazily
I am suspicious...
here...

**Comment by pitsi** [comment]
No issues here with invidious.tube, both inside the browser and in straw-viewer. On the other hand, I use ublock and I have set my browser (brave) to the strict level of content blocking setting.
The only flaw I saw was that clicking on
`https://invidious.tube`
redirected me to this
`https://invidious.tube/?ckattempt=1`

**Comment by OrionRandD** [comment]
Great!
I also have brave here.
Although I use waterfox with noscript, ublock, privacy badger
In all my browsers.
Unfortunatelly qutebrowser does not allow me to use noscript.
I also found that qtox and xscreensaver was eating lots of CPU power...
But, I can suspend those when I do not need them...
Thx for straw-viewer and keep up the good work...

**Comment by OrionRandD** [comment]
Could we make a list of the best working invidious instances here:
//yewtu.be    -> seems to work -> which others?

**Comment by pitsi** [comment]
Yewtu.be does not work for me as seen on the error above. It may be geo-restricted.
I updated straw-viewer to 0.0.9 last night, I set api_host to "auto" and I am happy so far. Stream load a lot faster than before.
Using the --debug parameter shows me the instance it currently uses, e.g. now it decided to use invidious.site
```
** GET https://instances.invidio.us/instances.json ==> 200 OK (2s)
:: Found 3 invidious instances.
:: Changed the instance to: https://invidious.site
```
while yesterday it used one located in France (invidious.fdn.fr).

**Comment by OrionRandD** [comment]
What are the steps for me to update straw-viewer?
Do I have to reinstall it again?
Thx

**Comment by pitsi** [comment]
Since you are on debian (like me) that does not package straw-viewer, these are the steps I do to "install/update" straw-viewer (and youtube-viewer in the past).

a) I have created 2 folders in my home dir, ~/bin and ~/lib. The first is used for the executable and the second one is for the libs it needs (the libs folder here on github). Also, this bit is needed in my ~/.bashrc to make everything work
```
PATH=$PATH:$HOME/bin/
PERL5LIB=$HOME/lib;export PERL5LIB
```
b) Every time a new version comes out, I download the zip file from the releases page and I extract straw-viewer inside ~/bin and the WWW folder inside ~/libs, so it looks like this
.
```
├── bin
│   ├── straw-viewer
.
├── lib
│   └── WWW
│       ├── StrawViewer
│       │   ├── Activities.pm
│       │   ├── Authentication.pm
│       │   ├── Channels.pm
│       │   ├── CommentThreads.pm
│       │   ├── GetCaption.pm
│       │   ├── GuideCategories.pm
│       │   ├── Itags.pm
│       │   ├── ParseJSON.pm
│       │   ├── ParseXML.pm
│       │   ├── PlaylistItems.pm
│       │   ├── Playlists.pm
│       │   ├── RegularExpressions.pm
│       │   ├── Search.pm
│       │   ├── Subscriptions.pm
│       │   ├── Utils.pm
│       │   ├── VideoCategories.pm
│       │   └── Videos.pm
│       ├── StrawViewer.pm

```
p.s. It obviously needs some perl dependencies, which I installed via apt.

**Comment by OrionRandD** [comment]
Thx for the hint ;)

**Comment by pitsi** [comment]
May I ask what you guys consider a very reliable instance of invidious? I have set "api_host" to "auto" and it used to work nicely, no matter the host it selected.
But, in the last couple of days, it selected some weird ones, with "rock" or "cafe" in their names if I recall correctly, adn they returned no results.

**Comment by trizen** [comment]
There was an YouTube change recently that affected the search results of all instances.

See: https://github.com/iv-org/invidious/issues/1422

**Comment by pitsi** [comment]
I am switching to that instance then. Thank you.
For me, every instance is slow compared to youtube (and youtube-viewer).

**Comment by OrionRandD** [comment]
@pitsi  "I am switching to that instance then." 
which instance? Could you be more specific? Thx

**Comment by pitsi** [comment]
The one suggested above by trizen to be a reliable one,` invidious.snopyta.org`.

**Comment by OrionRandD** [comment]
Ok. I've used
//invidious.snopyta.org/
before, and had some problems with it,

Now I've used
//yewtu.be

for some time without issues

**Comment by pitsi** [comment]
To be honest with you, I am really fed up with all those changes in invidious and/or youtube lately because I can not find an instance that works 100%. 
One does not return any results, one does return results for videos but not for channels, the next one is slow af and so on. I think that the numbers in instances.invidio.us simply do not reflect their true status.

And I am facing all these in kodi's addon for invidious, so I have "double checked" what say above. I respect both devs for their work, and I know it is not their fault, but some things need to be said. If the api has issues, the "best" instance is the one with the fewer problems... and I am still searching for it.

**Comment by OrionRandD** [comment]
Yeah. Me either.
By the way, I have used straw-viewer and most times it works fine.
Have a look here:
https://github.com/trizen/straw-viewer

**Comment by pitsi** [comment]
Hmmm... I know straw-viewer. In fact, this entire discussion is done in straw-viewer's github page :P

**Comment by pitsi** [comment]
Sorry for bringing this back up, but do you guys get... results from your searches? I get nothing for the last 3+ days and I think it is an api issue because I face the same thing on kodi's addon for invidious.

```
$ straw-viewer 

=>> Search for YouTube videos (:h for help)
> vevilos
:: Found 0 invidious instances: 
:: Found 9 invidious instances: invidious.snopyta.org invidious.tube invidious.kavin.rocks invidious.mservice.ru.com vid.encryptionin.space invidious.site invidious.fdn.fr invidious.zapashcanon.fr tube.connect.cafe
:: Changed the instance to: https://vid.encryptionin.space
** GET https://vid.encryptionin.space/api/v1/search?q=vevilos&type=video ==> 200 OK (1s)

[!] No video results!

=>> Select one or more videos to play (:h for help)
> 
```

**Comment by trizen** [comment]
@pitsi Yes, but most instances do not work. Workaround in https://github.com/trizen/straw-viewer/commit/09ce8a8b37194035934cc24d8e71058764ad7bb3. (I will tag a new version soon)

Two instances that work for me, are:

* invidious.kavin.rocks
* invidious.snopyta.org

**Comment by pitsi** [comment]
I had the snopyta one on both until Monday...
Thank you for your suggestion. They both work on straw viewer and return results... for now.

In the kodi addon though the story is a bit different. The snopyta one returns results for videos but not for channels, while the kavin one returns no results anywhere.

I am off to upgrade to v0.1.2 (and pipe-viewer to 0.0.4).
