### ISSUE TITLE
Not an ARRAY reference at /usr/bin/straw-viewer line 3659, <FIN> line 1.

### ISSUE THREAD

**Issue by andmars** [trizen/straw-viewer#24]
With straw-viewer-git-0.0.6.r7.g3faaf55-1 from AUR in Arch Linux I can open straw-viewer but every search gives me;
"[502 Bad Gateway] Error occurred on URL: https://invidio.us/api/v1/search?maxResults=20&part=snippet&q=stevie%20t&type=video

[!] No video results!
Not an ARRAY reference at /usr/bin/straw-viewer line 3659, <FIN> line 1."

**Comment by planetdeepak** [comment]
I'm also facing the same issue. Was working fine till yesterday. straw-viewer 0.0.6 on fedora 30

**Comment by trizen** [comment]
[invidio.us](https://invidio.us/) seems to be down.

The instance can be changed with `--api=url`:

```console
straw-viewer --api=invidious.snopyta.org
```

See also: https://github.com/trizen/straw-viewer#invidious-instances

**Comment by planetdeepak** [comment]
> ```
> straw-viewer --api=invidious.snopyta.org
> ```

This solved the problem. Thanks.
