### ISSUE TITLE
"[!] No video results!" with ":a#"

### ISSUE THREAD

**Issue by andmars** [trizen/straw-viewer#25]
When searching videos with straw-viewer and want to see the latest videos of a certain channel with ":a" and a number it doesn't give any results but shows "[!] No video results!" with the previous list of videos.

**Comment by trizen** [comment]
I cannot confirm this issue with `invidious.snopyta.org`. What instance are you using?

Additionally, use the `--debug` option to see if there are any errors.

**Comment by andmars** [comment]
The --debug gives;

=>> Select one or more videos to play (:h for help)
> :a1
** GET https://invidious.snopyta.org/api/v1/channels/UCPDis9pjXuqyI7RYLJ-TTSA/videos ==> 500 read timeout (1s)
** GET https://invidious.snopyta.org/api/v1/channels/UCPDis9pjXuqyI7RYLJ-TTSA/videos ==> 200 OK (2s)

[!] No video results!

**Comment by trizen** [comment]
Hmm... It seems to work only for some channels, but not for others. Although, it's not an issue of straw-viewer. It's an issue of invidious.

Changing the instance may help:

```console
straw-viewer --instance=invidious.13ad.de
```

For example, this works: https://invidious.13ad.de/api/v1/channels/UCXuqSBlHAE6Xw-yeJA0Tunw/videos
