### ISSUE TITLE
Convert videos on the same folder they are downloaded

### ISSUE THREAD

**Issue by celestialnavigation** [trizen/straw-viewer#26]
Hello
I'm enjoying straw-viewer a lot! Using the gtk frontend to watch videos and using the -d command with --convert-to=mp4 to convert them. I only wish the program would save the converted videos on the same folder I have set to download them instead of defaulting to my home folder, I could not find any configuration instructions on doing so.

**Comment by trizen** [comment]
Fixed in https://github.com/trizen/straw-viewer/commit/7620cc345421cd067dcec880b36e6cc41ac98cad. Thanks for reporting.

Notice that there is also `--prefer-mp4`, which will prefer MP4 (AVC) streams over WEBM (VP9), if available.
