### ISSUE TITLE
High temp and use of CPU on MPV - SOLVED

### ISSUE THREAD

**Issue by ciciolina** [trizen/straw-viewer#27]
Hi, i found this issue after install the application and run a video from youtube, my CPU consume more power and the temp jumps from 44-50c to 66-69c, im pretty sure its the resolution of the video and after look `straw-viewer --tricks` i found the config file: **/home/c/.config/straw-viewer/straw-viewer.conf** make a $sudo nano and search for the resolution line and found it   **resolution            => "best",**  after change "best" to "720p" and save the change my CPU and temp issue was solved. 

Feel free to change this value to the resolution you like, if you have the same issue try 720p or low and you will find this works like a charm, consume less resources like mpsyt after the change.  

Thank you for this amazing application, its beautiful!!!

PD. Im using a Thinkpad T440, Arch rolling release, KDE and last version of MPV, nvidia disabled (running with Intel).

**Comment by trizen** [comment]
Also setting `hfr => 0,` will help with slow GPUs when resolution is set to 1080p or higher.

**Comment by ciciolina** [comment]
> Also setting `hfr => 0,` will help with slow GPUs when resolution is set to 1080p or higher.

i apply your tip and works better, i know its not the space, but i have some issues to short the result list, i change `maxResults            => 10,` and `results_fixed_width   => 10,` and the list still remain on 20 (default), i dont know how overwrite this. Thank you!!!

**Comment by trizen** [comment]
Currently, the invidious API does not support specifying how many search results to return per request.

See also: https://github.com/trizen/straw-viewer/issues/12
