### ISSUE TITLE
JSON expected while parsing

### ISSUE THREAD

**Issue by arankaren** [trizen/straw-viewer#3]
Hello dear friend. Sometimes that warning message appears, what could it be?

`[JSON]: , or } expected while parsing object/hash, at character offset 123318 (before "endscreenClick":+["h...") at /usr/share/perl5/vendor_perl/WWW/StrawViewer/ParseJSON.pm line 34.`

**Comment by trizen** [comment]
Probably due to incomplete transfer of JSON data. If the issue persists, try changing the `api_host` in the configuration files.

The available instances of invidious are listed at: https://instances.invidio.us/

**Comment by arankaren** [comment]
Google is more restrictive than ever

**Comment by arankaren** [comment]
It would be better to use the entire invidious API. What is `get_video_info` used for? Example: `https://invidio.us/api/v1/videos/aqz-KE-bpKQ`

**Comment by trizen** [comment]
`get_video_info` is for extracting the audio/video URLs and info about closed-captions. The API of invidious does provide support for this, but sometimes the URLs do not work.
