### ISSUE TITLE
GTK fatal error

### ISSUE THREAD

**Issue by asakura42** [trizen/straw-viewer#33]
In `gtk-straw-viewer` every search fails with this output:

```
No results...
No results...
*** unhandled exception in callback:
***   No results...
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
FATAL: could not convert value 0 to enum type GtkResponseType at /usr/share/perl5/vendor_perl/Gtk3.pm line 285.
```

I use Arch Linux and installed `straw-viewer-git` from AUR.

**Comment by trizen** [comment]
There was an YouTube change recently that affected the search results on all invidious instances. The issue got fixed upstream (https://github.com/iv-org/invidious/issues/1422), but it may take some time until all instances are updated with the fix.

Meanwhile, try setting in the Preferences window:

```perl
api_host => "invidious.snopyta.org",
```

or

```perl
api_host => "invidious.zapashcanon.fr",
```
