### ISSUE TITLE
perl errors with master 6d8bc

### ISSUE THREAD

**Issue by zenny** [trizen/straw-viewer#35]
Hi,

Just pulled the https://github.com/trizen/straw-viewer/commit/6d8bc720768183fe59ec1d6e380e5a8c1f8620b5, and I get:

```
Can't load '/usr/lib/perl5/site_perl/auto/HTML/Parser/Parser.so' for module HTML::Parser: /usr/lib/perl5/site_perl/auto/HTML/Parser/Parser.so: undefined symbol: Perl__is_utf8_char_helper at /usr/share/perl5/core_perl/XSLoader.pm line 93.
 at /usr/lib/perl5/site_perl/HTML/Parser.pm line 11.
Compilation failed in require at /usr/lib/perl5/site_perl/HTML/Entities.pm line 152.
Compilation failed in require at ../lib/WWW/StrawViewer/Utils.pm line 464.
```

I tried without installing (https://github.com/trizen/straw-viewer#try) with the same error.

HTML::Parser is already installed:

```
# xbps-install -S perl-HTML-Parser
...
Package `perl-HTML-Parser' already installed.
```

**Comment by trizen** [comment]
Hi,

Try to remove `/usr/lib/perl5/site_perl/auto/HTML/Parser/Parser.so` then reinstall [HTML::Parser](https://metacpan.org/pod/HTML::Parser).

**Comment by zenny** [comment]
> /usr/lib/perl5/site_perl/auto/HTML/Parser/Parser.so

Did accordingly, but landed with another error:

```
HTML::Parser object version 3.75 does not match bootstrap parameter 3.72 at /usr/lib/perl5/core_perl/DynaLoader.pm line 210.
Compilation failed in require at /usr/lib/perl5/site_perl/HTML/Entities.pm line 152.
Compilation failed in require at ../lib/WWW/StrawViewer/Utils.pm line 464.
```

**Comment by trizen** [comment]
It looks like there is still HTML::Parser version 3.72 installed. Although, the package in Void Linux was already upgraded to 3.75 ([diff](https://github.com/void-linux/void-packages/commit/eeac1a581a9ec22b3e58178e867119aba1aaaf1b#diff-8b50869a101d575b752cf95ec9778df2f86e282b38f3d0de47871522e3bdff79)).

Most probably, the failing modules were built with an older version `perl`, which recently got upgraded to `perl-5.32`, hence the errors.

I recommend rebuilding all the Perl packages that have parts of code written in C.
If there are still issues, you can try to remove `/usr/lib/perl5/site_perl` entirely and start clean.

For an alternative solution, see: https://www.perlmonks.org/?node_id=1056103

Not really a straw-viewer, so I will close this.
