### ISSUE TITLE
Month name in details has broken Cyrillic encoding

### ISSUE THREAD

**Issue by Flashwalker** [trizen/straw-viewer#37]
Month name in details has broken Cyrillic encoding.  
Here is a self-explained screenshots: 
 
![2020-11-21_00-57](https://user-images.githubusercontent.com/2188215/99854103-3ee13480-2b95-11eb-8b42-005d54d7a95a.jpg)
![2020-11-21_00-5](https://user-images.githubusercontent.com/2188215/99854113-430d5200-2b95-11eb-9319-1f5aeb880e4b.jpg)

**Comment by trizen** [comment]
Hi. Thanks for reporting.

Please check the above commit (https://github.com/trizen/straw-viewer/commit/51abf34a430546982794088bb8758580bbc7f1ae) to see if it fixes the issue.

**Comment by Flashwalker** [comment]
Yes, encoding is ok now.

**Comment by Flashwalker** [comment]
Looks like same issue in Errors window  
![Снимок экрана_2021-01-08_18-32-48](https://user-images.githubusercontent.com/2188215/104033411-8ae94680-51e0-11eb-808f-0553214c7621.jpg)

**Comment by trizen** [comment]
Thanks for reporting. Please test the above commit, which includes a workaround for this issue.

**Comment by Flashwalker** [comment]
Yeap, it's ok now
