### ISSUE TITLE
SSL connect attempt failed 

### ISSUE THREAD

**Issue by 097115** [trizen/straw-viewer#39]
Got this error when starting (`./straw-viewer --api=auto <SEARCH-TERM>`):

    500 Can't connect to invidious.snopyta.org:443 (LWP::Protocol::https::Socket: SSL connect attempt failed with unknown error error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)

Something I have to update may be?

**Comment by trizen** [comment]
I can't confirm this issue. What's your version of `openssl`?

```
$ openssl version
```

**Comment by 097115** [comment]
`OpenSSL 1.1.1i`

But... it's macOS, and openssl is installed via Homebrew (and located in in`/usr/local/opt/openssl@1.1/bin/openssl`). So, `straw-viewer` is probably somehow using the system openssl from `/usr/bin/openssl`, which is indeed quite old, `OpenSSL 0.9.8zh`...

Any way I can point it to the newest one?

**Comment by trizen** [comment]
Not sure. Check to see which version of `openssl` is used by `Net::SSLeay`:

```
perl -MNet::SSLeay -E 'say Net::SSLeay::SSLeay_version'
```

Alternatively, try to reinstall `Net::SSLeay`.

**Comment by 097115** [comment]
> You may also want to try to reinstall Net::SSLeay.

Yep, that solved it. Thanks :)
