### ISSUE TITLE
Sound is going off randomly while playing videos 

### ISSUE THREAD

**Issue by chainfrost** [trizen/straw-viewer#4]
I have moved from GTK-viewer and would like to inform you some problems I have found:

1- When you open a video that starts normally without any problem, but after certain time sound is going off and only video stays for playing.
2 - When you want to forward/rewind the video from keyboard, playing window closes itself and you have to open video again.

I checked first problem on various videos, I think that is not related with the video itself.

I am looking for your suggestions. Thanks for your work.

**Comment by trizen** [comment]
I cannot confirm this issue with `mpv 0.32.0`. It may be an issue with your video player. What player are you using and what version?

**Comment by chainfrost** [comment]
Linux version: 5.4.23-1-MANJARO
Video player : mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects

ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2

**Comment by chainfrost** [comment]
Thanks for your reply. After your info, I checked preferences and found **mplayer** is defined as default player. I changed into **mpv** and problem solved. 
Thanks for your help :)
