### ISSUE TITLE
Error: video unavailable

### ISSUE THREAD

**Issue by dancaer69** [trizen/straw-viewer#8]
I just downloaded and install the latest release but every video I try to play in straw-viewer doesn't load and I get the error:
```
ERROR: IIlcwlw9XVk: YouTube said: This video is unavailable.
do_connect: could not connect to socket
connect: No such file or directory
```
I tried to input the above video directly in browser address:
`https://www.youtube.com/watch?v=IIlcwlw9XVk`
and then it loads and plays without problem.

**Comment by trizen** [comment]
I cannot confirm this issue...

Make sure to have the latest version of `youtube-dl` installed.
