### ISSUE TITLE
Feature request: next video shortkey

### ISSUE THREAD

**Issue by tobip** [trizen/straw-viewer#9]
straw-viewer works like a charm for me!
Unless I missed something, I couldn't find a "skip to next video" shortkey while playing multiple videos, e.g. using the -A option.
As a workaround at the moment if I want to skip the playing video I scroll all the way to the end using the arrow up key.

**Comment by paretje** [comment]
Going back would be nice as well. One option might be to (have the option to) pass all video's at once to the player, then the user can use normal player shortcuts to navigate? That would resolve https://github.com/trizen/youtube-viewer/issues/286 as well.

**Comment by trizen** [comment]
If you use `mpv`, you can press `Q` for closing the current video. Additionally, `CTRL+C` stops all videos.
